// server/src/routes/formSubmissionRoutes/schemesOffers.ts
import { Request, Response, Express } from 'express';
import { db } from '../../db/db';
import { schemesOffers } from '../../db/schema';
import { z } from 'zod';

// -------- Helpers (from addDealer.ts) --------

// empty string -> null for strings
export const strOrNull = z.preprocess((val) => {
  if (val === '') return null;
  if (typeof val === 'string') {
    const t = val.trim();
    return t === '' ? null : t;
  }
  return val;
}, z.string().nullable().optional());

// empty string -> null for dates (and coerce)
export const dateOrNull = z.preprocess((val) => {
  if (val === '' || val === null || val === undefined) return null;
  try {
    const d = new Date(String(val));
    // Check for invalid date
    if (isNaN(d.getTime())) return null;
    return d;
  } catch {
    return null;
  }
}, z.date().nullable().optional());

// -------- Input Schema --------

// Zod schema for validating the request body for a new scheme/offer
const insertSchemeOfferSchema = z.object({
  name: z.string().min(1, "Name is required"),
  description: strOrNull,
  startDate: dateOrNull,
  endDate: dateOrNull,
}).strict(); // Use .strict() to catch any extra fields

export default function setupSchemesOffersPostRoutes(app: Express) {
  
  app.post('/api/schemes-offers', async (req: Request, res: Response) => {
    const tableName = 'Scheme/Offer';
    try {
      // 1. Validate and coerce the request body
      const validated = insertSchemeOfferSchema.parse(req.body);

      // 2. Map validated data to the database schema
      // 'id' will be auto-generated by the database (defaultRandom)
      const insertData = {
        name: validated.name,
        description: validated.description ?? null,
        startDate: validated.startDate ?? null, // Zod helper ensures this is a Date or null
        endDate: validated.endDate ?? null,     // Zod helper ensures this is a Date or null
      };

      // 3. Insert the new record
      const [newRecord] = await db
        .insert(schemesOffers)
        .values(insertData)
        .returning();

      // 4. Send success response
      return res.status(201).json({
        success: true,
        message: `${tableName} created successfully`,
        data: newRecord,
      });

    } catch (err: any) {
      // 5. Handle errors
      console.error(`Create ${tableName} error:`, {
        message: err?.message,
        code: err?.code,
        detail: err?.detail,
      });

      // Handle Zod validation errors
      if (err instanceof z.ZodError) {
        return res.status(400).json({ 
          success: false, 
          error: 'Validation failed', 
          details: err.errors.map(e => ({
            field: e.path.join('.'),
            message: e.message,
          })) 
        });
      }

      // Handle other database or server errors
      return res.status(500).json({ 
        success: false, 
        error: `Failed to create ${tableName}`, 
        details: err?.message ?? 'Unknown error' 
      });
    }
  });

  console.log('✅ Schemes/Offers POST endpoint setup complete');
}